import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/app/_components/navigation";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
  title: "Rikin Katyal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Navigation />
        <div className="container md:max-w-2xl mx-auto max-w-none">
          {children}
        </div>
      </body>
    </html>
  );
}
